name: Manual trigger

on:
  workflow_dispatch:

jobs:
  check-out:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with: 
          sparse-checkout: |
            spec
          repository: ${{ secrets.SERVER_REPO }}
          token: ${{ secrets.PAT_TOKEN }}
      - name: Debugging Step
        run: pwd && ls -l
      - name: Generate code
        uses: hatamiarash7/openapi-generator@v0.2.0
        with:
          generator: kotlin
          openapi-file: HelloAPI.json

      # Do anything you want with the generated code
      - name: Do anything
        run: ls -l kotlin-client
