name: Manual trigger

on:
  workflow_dispatch:

jobs:
  check-out:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with: 
          sparse-checkout: |
            spec
          repository: ${{ secrets.SERVER_REPO }}
          token: ${{ secrets.PAT_TOKEN }}
      - name: Swagger Codegen CLI
        uses: CapsLock-Studio/swagger-codegen-action@74d06d53d1cdb23a7715f487361a39c8885d60f9
        with: 
          language: kotlin
          input: /github/workspace/spec/HelloAPI.json
          action: generate
      - name: Debugging
        run: ls -l $GITHUB_WORKSPACE
      - name: Zip
        uses: TonyBogdanov/zip@1.0
        with:
            args: zip -qq -r ./HelloAPI.zip /github/workspace/
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload zip to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./HelloAPI.zip
          asset_name: HelloAPI.zip
          asset_content_type: application/zip
