name: Manual trigger

on:
  workflow_dispatch:

jobs:
  check-out:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with: 
          sparse-checkout: |
            spec
          repository: ${{ secrets.SERVER_REPO }}
          token: ${{ secrets.PAT_TOKEN }}
